#!/bin/bash

# idk but like
SOURCE_PATH="/test_dir"
SOURCE_SHORTNAME="test"
OUTPUT_PATH="/"
DATE="test_date"
OUTPUT_FILENAME="${SOURCE_SHORTNAME}_registry_${DATE}"
echo "DIRECTORY REGISTRY OF 
	SHORTNAME: ${SOURCE_SHORTNAME}
	PATH: ${SOURCE_PATH}
	DATE: ${DATE}
	OUTPUT: ${OUTPUT_PATH}/${OUTPUT_FILENAME}.txt
	-------" >> "$OUTPUT_PATH/${OUTPUT_FILENAME}.txt"
# ls  >> "$OUTPUT_PATH/${OUTPUT_FILENAME}.txt"
